server:
  port: 8003
spring:
  application:
    name: ruby-product
    cloud:
      nacos:
        config:
          server-addr: 127.0.0.1:8848
        discovery:
          server-addr: 127.0.0.1:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource             # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver               #驱动包
    url: jdbc:mysql://rm-bp1l1021y100jllwrbo.mysql.rds.aliyuncs.com:3306/db_sca?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=GMT%2B8&characterEncoding=utf8 # 数据库名称
    username: neil
    password: Pass1234

    initialSize: 1  # 连接池的配置信息:初始化大小，最小，最大
    minIdle: 1
    maxActive: 10
    maxWait: 60000 # 配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 30000  # 配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 1 FROM DUAL #验证库是否正常sql
    testWhileIdle: true  #空闲时验证，防止连接断开
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true  # 打开PSCache，并且指定每个连接上PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录

ruby:
  druid:
    username: neil
    password: Pass1234