server:
  port: 8001

spring:
  application:
    name: system
    cloud:
      nacos:
        discovery:
          server-addr: 127.0.0.1:8848

ruby:
  druid:
    username: neil
    password: Pass1234